<?php
/**
 * Auto generated by prado-cli.php on 2007-12-14 09:59:16.
 * 
 * @author Matthew Katsenes <psalakanthos@gmail.com>
 * @copyright Copyright (c) 2007 Matthew Katsenes
 * @package tiro-input
 * @subpackage database
 * @version tiro-input side v. 0.1
 */
class NewsRecord extends TActiveRecord
{
	const TABLE='newsItems';

	public $item_id;
	public $author_id;
	public $slug;
	public $full_text;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public $author;
	public static $RELATIONS = array(
		'author' => array(self::BELONGS_TO, 'AdminRecord'),
	);
}
?>