<?php
/**
 * Auto generated by prado-cli.php on 2007-12-14 09:57:08.
 */
class AdminRecord extends TActiveRecord
{
	const TABLE='adminUsers';

	public $username;
	public $password;
	public $email;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	/**
	 * ActiveRecord array of NewsRecord objects.
	 */
	public $newsItems=array();
	
	public static $RELATIONS=array
	(
		'newsItems' => array(self::HAS_MANY, 'NewsRecord'),
	);
}
?>