<?php
/**
 * Auto generated by prado-cli.php on 2007-12-10 11:50:36.
 */
class NewsItemRecord extends TActiveRecord
{
	const TABLE='newsItems';

	public $item_id;
	public $author_id;
	public $slug;
	public $full_text;
	public $time;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public $author; // holds an UserRecord

	public static $RELATIONS=array
	(
		'author' => array(self::BELONGS_TO, 'UserRecord'),
	);
}
?>