<?php
/**
 * Auto generated by prado-cli.php on 2007-12-14 09:57:27.
 * 
 * @author Matthew Katsenes <psalakanthos@gmail.com>
 * @copyright Copyright (c) 2007 Matthew Katsenes
 * @package tiro-input
 * @subpackage database
 * @version tiro-input side v. 0.1
 */
class TeacherRecord extends TActiveRecord
{
	const TABLE='teacherUsers';

	public $username;
	public $password;
	public $first_name;
	public $middle_name;
	public $last_name;
	public $email;
	public $website;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public $texts = array();
	public $students = array();
	
	public static $RELATIONS = array(
		'texts' => array(self::HAS_MANY, 'TextRecord'),
		'students' => array(self::HAS_MANY, 'StudentRecord'),
	);
}
?>