<?php
/**
 * Auto generated by prado-cli.php on 2007-12-14 09:57:27.
 */
class TeacherRecord extends TActiveRecord
{
	const TABLE='teacherUsers';

	public $username;
	public $password;
	public $email;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public $texts = array();
	public $students = array();
	
	public static $RELATIONS = array(
		'texts' => array(self::HAS_MANY, 'TextRecord'),
		'students' => array(self::HAS_MANY, 'StudentRecord'),
	);
}
?>