<?php
/**
 * Auto generated by prado-cli.php on 2007-11-18 12:13:19.
 */
class TextRecord extends TActiveRecord
{
	const TABLE='texts';

	public $text_id;
	public $author_id;
	public $create_time;
	public $title;
	public $status;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public $author; //holds an UserRecord

	public static $RELATIONS=array
	(
		'author' => array(self::BELONGS_TO, 'UserRecord'),
	);
}
?>