<?php
/**
 * Auto generated by prado-cli.php on 2007-11-18 12:13:00.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='users';

	public $username;
	public $password;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

    public $texts=array(); //holds an array of TextRecord

    public static $RELATIONS=array
    (
        'texts' => array(self::HAS_MANY, 'TextRecord'),
    );
}
?>